<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>inspector</AssemblyName>
    <GameCoreDir>$(BepInExCoreDir)</GameCoreDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>$(GameCoreDir)/Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
